########################
##### EXPERIMENTAL #####
########################

#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHOME PRE-BUILT - Wall_Display variation by https://github.com/MichaelHeimann           #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
---
substitutions:
  heater_relay: "1"  # Possible values: 1/2
  temp_min: "16"     # Min supported temperature is 40°F
  temp_max: "26"     # Max supported temperature is 80°F
  temp_step: "0.5"   # Temperature granularity is 1°F

packages:
  prebuilt_package: !include nspanel_esphome_prebuilt.yaml
  climate_heat: !include ../esphome/nspanel_esphome_addon_climate_heat.yaml

dashboard_import:
  package_import_url: github://Blackymas/NSPanel_HA_Blueprint/prebuilt/wall_display.yaml@main
  import_full_config: false

esphome:
  project:
    name: esphome.Wall_Display
  platformio_options:
    build_flags:
      - -D NSPANEL_HA_BLUEPRINT_PREBUILT_WALL_DISPLAY

text:
  - id: !extend fw_url
    initial_value: "https://raw.githubusercontent.com/Blackymas/NSPanel_HA_Blueprint/main/prebuilt/wall_display.bin"
...
