#####################################################################################################
##### NSPANEL ESPHOME created by Blackymas - https://github.com/Blackymas/NSPanel_HA_Blueprint  #####
##### ESPHome Add-on for Climate control - Cool                                                 #####
##### PLEASE only make changes if it is necessary and also the required knowledge is available. #####
##### For normal use with the Blueprint, no changes are necessary.                              #####
#####################################################################################################
##### ATTENTION: This will add climate elements to the core system and requires the core part.  #####
#####################################################################################################

substitutions:
  ### Local thermostat defaults ###
  # https://esphome.io/components/climate/thermostat.html
  cooler_relay: "0" # Select 1 for "Relay 1", 2 for "Relay 2" or "0" to a dummy switch/disabled
  # https://esphome.io/components/climate/index.html#base-climate-configuration
  temp_min: "15"
  temp_max: "45"

  ##### DO NOT CHANGE THIS #####
  addon_climate_cool: "true"
  addon_climate_heat: "false"
  ##############################

climate:
  - id: !extend thermostat_embedded
    min_cooling_off_time: ${min_off_time}s
    min_cooling_run_time: ${min_run_time}s
    cool_action:
      - switch.turn_on: relay_${cooler_relay}
    preset:
      - name: "Off"
        default_target_temperature_high: ${temp_min} ${temp_units}
        mode: "off"
      - name: Home
        default_target_temperature_high: 21 ${temp_units}

packages:
  core_package: !include nspanel_esphome_addon_climate_base.yaml
