---
substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  core_package: !include ../nspanel_esphome.yaml  # Core package
  advanced_package: !include ../advanced/esphome/nspanel_esphome_advanced.yaml
  # addon_climate_heat: !include ../nspanel_esphome_addon_climate_heat.yaml
  addon_climate_cool: !include ../nspanel_esphome_addon_climate_cool.yaml
  # addon_climate_dual: !include ../nspanel_esphome_addon_climate_dual.yaml

esp32:
  framework:
    type: esp-idf

bluetooth_proxy:

# Set Wi-Fi power save mode to "LIGHT" as required for Bluetooth on ESP32
wifi:
  power_save_mode: LIGHT
...
