substitutions:
  device_name: nspanel
  wifi_ssid: "nspanel"
  wifi_password: "NSPanel_HA_Blueprint"
  nextion_update_url: "https://github.com/Blackymas/NSPanel_HA_Blueprint/dummy"

packages:
  core_package: !include ../nspanel_esphome.yaml # Core package
  advanced_package: !include ../advanced/esphome/nspanel_esphome_advanced.yaml
  #addon_climate_heat: !include ../advanced/esphome/nspanel_esphome_addon_climate_heat.yaml
  #addon_climate_cool: !include ../advanced/esphome/nspanel_esphome_addon_climate_cool.yaml
