---
name: Bug Report
description: |
  We aim to keep everything running smoothly.
  Please fill out the form with details to help us identify and address the issue.
title: "`Bug` "
labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!

        We wanna everything always working like a charm, so please let us know where our attention is needed.

        > [!WARNING]
        > Remember to omit any private or sensitive information, as this bug report will be publicly visible.

  - type: markdown
    attributes:
      value: |
        ## Please provide the version numbers for TFT, ESPHome, and Blueprint

        You can find these version numbers on the boot screen of your device.
        The Blueprint version can also be found in the automation where the blueprint is set.

  - type: input
    attributes:
      label: TFT Version
      description: Enter the version number of TFT.
      placeholder: e.g., 4.1.4
    validations:
      required: false

  - type: input
    attributes:
      label: ESPHome Version
      description: Enter the version number of ESPHome.
      placeholder: e.g., 4.1.4
    validations:
      required: false

  - type: input
    attributes:
      label: Blueprint Version
      description: Enter the version number of the Blueprint.
      placeholder: e.g., 4.1.4
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Panel Model
      description: Select your NSPanel model.
      options:
        - NSPanel EU Model
        - NSPanel US Model
        - NSPanel US Model (Landscape)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Please provide details about the bug

  - type: input
    attributes:
      label: What is the bug?
      description: A clear and concise description of what the bug is.
      placeholder: e.g., When I try this, I'm getting this result, while I was expecting that...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior. Please feel free to share pictures of your screen or anything relevant.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Please provide some additional info, when possible

  - type: textarea
    attributes:
      label: Your panel's YAML
      description: Please provide device's YAML configuration.
      render: yaml
      placeholder: |
        substitutions:
          # Settings - Editable values
          device_name: "YOUR_NSPANEL_NAME"
          wifi_ssid: !secret wifi_ssid
          wifi_password: !secret wifi_password

          nextion_update_url: "http://homeassistant.local:8123/local/nspanel_us.tft"

          # Add-on configuration (if needed)
          ## Add-on climate
          heater_relay: "1"  # Possible values: "1" or "2"

        # Customization area
        ##### My customization - Start #####
        ##### My customization - End #####

        # Core and optional configurations
        packages:
          remote_package:
            url: https://github.com/Blackymas/NSPanel_HA_Blueprint
            ref: main
            files:
              - nspanel_esphome.yaml # Core package
              # Optional advanced and add-on configurations
              # - advanced/esphome/nspanel_esphome_advanced.yaml
              # - nspanel_esphome_addon_climate_cool.yaml
              - nspanel_esphome_addon_climate_heat.yaml
              # - nspanel_esphome_addon_climate_dual.yaml
            refresh: 300s

        esp32:
          framework:
            type: esp-idf
    validations:
      required: false

  - type: textarea
    attributes:
      label: ESPHome logs
      description: You can get this by clicking the **Logs** button related to your device on ESPHome Dashboard.
      render: logs
    validations:
      required: false

  - type: textarea
    attributes:
      label: Home Assistant logs
      description: You can get this from **Settings** > **System** > [**Logs**](https://my.home-assistant.io/redirect/logs/) in your Home Assistant.
      render: logs
    validations:
      required: false
...
