---
blank_issues_enabled: false
contact_links:
  - name: Discussions area
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint/discussions
    about: This is your go-to space for community conversations, questions, idea sharing, and collaboration around our project.
  - name: Troubleshooting TFT Transfer
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/tft_upload.md
    about: Try this guide first if you are having issues to transfer a TFT file.
  - name: Compiling Errors Guide
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/error_compiling.md
    about: Experiencing Compile Errors? Check This Guide!
  - name: Getting Started with NSPanel HA Blueprint
    url: https://github.com/Blackymas/NSPanel_HA_Blueprint/blob/main/docs/install.md
    about: This is the starting poing for installing a new NSPanel HA Blueprint.
...
