---
name: Enhancement Request
description: Suggest an idea for this project
title: "`Enhancement` "
labels: [Enhancement]
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to suggest an enhancement!"

  - type: input
    attributes:
      label: Enhancement Summary
      description: A brief summary of the enhancement.
      placeholder: e.g., Add support for XYZ feature...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Detailed Description
      description: Please provide a detailed description of the enhancement. Include any specific use cases or functionality you envision.
      placeholder: "Describe the enhancement in detail..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Context
      description: "Provide any additional context or screenshots that might help us understand the enhancement better."
      placeholder: "Add any other context or screenshots about the enhancement request here."
...
