---
name: Question
description: Ask a question about this project
title: "`Question` "
labels: [Question]
body:
  - type: markdown
    attributes:
      value: "We're here to help! Ask your question below."

  - type: input
    attributes:
      label: Question
      description: What do you want to ask?
      placeholder: e.g., How do I configure XYZ?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Details
      description: Provide any additional details or context for your question.
      placeholder: "Add any more details about your question here."
...
