---
name: Update Tags

# yamllint disable-line rule:truthy
on:
  release:
    types: [published]

jobs:
  update-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: '0'

      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Move and push stable tag
        run: |
          git tag -f stable ${{ github.event.release.tag_name }}
          git push -f origin stable

      - name: Move and push latest tag
        run: |
          git tag -f latest ${{ github.event.release.tag_name }}
          git push -f origin latest
...
