name: Validate Blueprint YAML

on:
  push:
    paths:
      - "nspanel_blueprint.yaml"
  pull_request:
    paths:
      - "nspanel_blueprint.yaml"
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  code_scan:
    name: Validate Blueprint YAML
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Validate nspanel_blueprint.yaml
        run: yamllint -c "./.yamllint/rules.yml" nspanel_blueprint.yaml
